language: python
python:
  # CPython versions
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly" # nightly build
  # PyPy versions
  - "pypy"
  - "pypy3"
install:
  - pip install . # install package
  - pip install codecov
script:
  - coverage run --branch --source=updatable run_tests.py
  - coverage xml
after_success:
  - codecov

stages:
- lint
- test

jobs:
  include:
  - stage: lint
    python: 3.7
    install: pip install pylama
    script: pylama ./updatable ./test
